### ISSUE TITLE
Missing chrome types

### ISSUE THREAD

**Issue by cathykc** [dkthehuman/extension-starter-kit#1]
# Missing chrome types
### Problem 
Running `npm run build` to package for production produces following errors:
```
TS2304: Cannot find name 'chrome'.
```

### Solution
Run `npm install --save @types/chrome`

**Comment by dkthehuman** [comment]
Hi Cathy! 

The Extension Starter Kit uses [webextension-polyfill](https://github.com/mozilla/webextension-polyfill) and the Typescript wrapper [webextension-polyfill-ts](https://github.com/Lusito/webextension-polyfill-ts), which means that you won't ever need to reference `chrome`. The benefit of using the polyfill is that your extension will support both Chrome and Firefox automatically.

Everywhere you'd use `chrome` (e.g. `chrome.storage`), just replace it with `browser` and the polyfill will take care of the rest!

**Comment by cathykc** [comment]
OK
